//get all posts
GET http://localhost:3000/posts

###

POST http://localhost:3000/posts
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc0MWNkYWFiYjFhYjVmMTgzMGIxOTciLCJpYXQiOjE3MzU2NjMwNDIsImV4cCI6MTczNTY2NjY0Mn0.680KF603pqonag4GBQIWwYFWJOep1J7z-ai-AdkDHR0
Content-Type: application/json

{
    "title": "title",
    "content": "content",
    "owner": "owner"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "example@mail.com",
    "password": "1234"
}

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "example@mail.com",
    "password": "1234"
} 

###


POST http://localhost:3000/auth/logout
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc0MjA3NzRmNzRiMThkNGE4ZGE2NWMiLCJyYW5kb20iOiIwLjA1OTQxNjg4MTgyODI2MDEwNCIsImlhdCI6MTczNTY2MzgyM30.Vhv7C8Fg-erCtLRsuzy0iZUPXjHVhwz2X6F0up1Qupc

###

POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc0MzM0MjcwYmJjMzQ2OTNiNWZkNmYiLCJyYW5kb20iOiIwLjAxODE3NTM1MTM2MDE3MTAxIiwiaWF0IjoxNzM1NjY4NTQ5fQ.LSztMFlxx5HN6PYD0OiV8OIFWLMOHnESC5G4_qCRy6Q"
}